#undef EAZY_USERDEFINED_LITERALS_CHAR

#undef EZL_MAKE_CHAR_CPL_VA
#undef EZL_MAKE_CHAR_CPL
#undef EZL_MAKE_CHAR_CPL_D
#undef EZL_MAKE_CHAR
#undef EZL_MAKE_CHAR_I
#undef EZL_MAKE_CHAR_C

#undef EZL_MAKE_WCHAR_CPL_VA
#undef EZL_MAKE_WCHAR_CPL
#undef EZL_MAKE_WCHAR_CPL_D
#undef EZL_MAKE_WCHAR
#undef EZL_MAKE_WCHAR_I
#undef EZL_MAKE_WCHAR_C

#undef EZL_MAKE_CHAR16_CPL_VA
#undef EZL_MAKE_CHAR16_CPL
#undef EZL_MAKE_CHAR16_CPL_D
#undef EZL_MAKE_CHAR16
#undef EZL_MAKE_CHAR16_I
#undef EZL_MAKE_CHAR16_C

#undef EZL_MAKE_CHAR32_CPL_VA
#undef EZL_MAKE_CHAR32_CPL
#undef EZL_MAKE_CHAR32_CPL_D
#undef EZL_MAKE_CHAR32
#undef EZL_MAKE_CHAR32_I
#undef EZL_MAKE_CHAR32_C
