/**
 * ezl_str_undef.hpp
 * Etienne Boespflug - 2018
 *
 * This software has no license, feel free to use,
 * modify and distribute.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY
 * OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
 * LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
 * CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR
 * THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

#undef EAZY_USERDEFINED_LITERALS_STR

#undef EZL_MAKE_STR_CPL
#undef EZL_MAKE_STR_CPL_D
#undef EZL_MAKE_STR
#undef EZL_MAKE_STR_I
#undef EZL_MAKE_STR_C

#undef EZL_MAKE_WSTR_CPL
#undef EZL_MAKE_WSTR_CPL_D
#undef EZL_MAKE_WSTR
#undef EZL_MAKE_WSTR_I
#undef EZL_MAKE_WSTR_C

#undef EZL_MAKE_STR16_CPL
#undef EZL_MAKE_STR16_CPL_D
#undef EZL_MAKE_STR16
#undef EZL_MAKE_STR16_I
#undef EZL_MAKE_STR16_C

#undef EZL_MAKE_STR32_CPL
#undef EZL_MAKE_STR32_CPL_D
#undef EZL_MAKE_STR32
#undef EZL_MAKE_STR32_I
#undef EZL_MAKE_STR32_C
