#undef EAZY_USERDEFINED_LITERALS_STR

#undef EZL_MAKE_STR_CPL_VA
#undef EZL_MAKE_STR_CPL
#undef EZL_MAKE_STR_CPL_D
#undef EZL_MAKE_STR
#undef EZL_MAKE_STR_I
#undef EZL_MAKE_STR_C

#undef EZL_MAKE_WSTR_CPL_VA
#undef EZL_MAKE_WSTR_CPL
#undef EZL_MAKE_WSTR_CPL_D
#undef EZL_MAKE_WSTR
#undef EZL_MAKE_WSTR_I
#undef EZL_MAKE_WSTR_C

#undef EZL_MAKE_STR16_CPL_VA
#undef EZL_MAKE_STR16_CPL
#undef EZL_MAKE_STR16_CPL_D
#undef EZL_MAKE_STR16
#undef EZL_MAKE_STR16_I
#undef EZL_MAKE_STR16_C

#undef EZL_MAKE_STR32_CPL_VA
#undef EZL_MAKE_STR32_CPL
#undef EZL_MAKE_STR32_CPL_D
#undef EZL_MAKE_STR32
#undef EZL_MAKE_STR32_I
#undef EZL_MAKE_STR32_C
