/**
 * ezl_char_undef.hpp
 * Etienne Boespflug - 2018
 *
 * This software has no license, feel free to use,
 * modify and distribute.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY
 * OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
 * LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
 * CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR
 * THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

#undef EAZY_USERDEFINED_LITERALS_CHAR

#undef EZL_MAKE_CHAR_CPL
#undef EZL_MAKE_CHAR_CPL_D
#undef EZL_MAKE_CHAR
#undef EZL_MAKE_CHAR_I
#undef EZL_MAKE_CHAR_C

#undef EZL_MAKE_WCHAR_CPL
#undef EZL_MAKE_WCHAR_CPL_D
#undef EZL_MAKE_WCHAR
#undef EZL_MAKE_WCHAR_I
#undef EZL_MAKE_WCHAR_C

#undef EZL_MAKE_CHAR16_CPL
#undef EZL_MAKE_CHAR16_CPL_D
#undef EZL_MAKE_CHAR16
#undef EZL_MAKE_CHAR16_I
#undef EZL_MAKE_CHAR16_C

#undef EZL_MAKE_CHAR32_CPL
#undef EZL_MAKE_CHAR32_CPL_D
#undef EZL_MAKE_CHAR32
#undef EZL_MAKE_CHAR32_I
#undef EZL_MAKE_CHAR32_C
