/**
 * ezl_num_undef.hpp
 * Etienne Boespflug - 2018
 *
 * This file contains preprocessor undef directives
 * corresponding to the ezl_num.hpp header.
 *
 * This software has no license, feel free to use,
 * modify and distribute.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY
 * OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT
 * LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE.
 * IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY
 * CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR
 * THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

#undef EAZY_USERDEFINED_LITERALS_NUM

#undef EZL_MAKE_INT_CPL
#undef EZL_MAKE_INT_CPL_D
#undef EZL_MAKE_INT
#undef EZL_MAKE_INT_I
#undef EZL_MAKE_INT_C

#undef EZL_MAKE_FLOAT_CPL
#undef EZL_MAKE_FLOAT_CPL_D
#undef EZL_MAKE_FLOAT
#undef EZL_MAKE_FLOAT_I
#undef EZL_MAKE_FLOAT_C
