#undef LIB_EAZY_USERDEFINED_LITERALS

#undef EZL_STRINGCAT_FINAL_
#undef EZL_STRINGCAT
#undef EZL_JOIN

#undef EZL_MAKE_STR_CPLVA
#undef EZL_MAKE_STR_CPL
#undef EZL_MAKE_STR_
#undef EZL_MAKE_STR
#undef EZL_MAKE_STR_C

#undef EZL_MAKE
#undef EZL_MAKE_C
