#undef EAZY_USERDEFINED_LITERALS_NUM

#undef EZL_MAKE_INT_CPL
#undef EZL_MAKE_INT_CPL_D
#undef EZL_MAKE_INT
#undef EZL_MAKE_INT_I
#undef EZL_MAKE_INT_C

#undef EZL_MAKE_FLOAT_CPL
#undef EZL_MAKE_FLOAT_CPL_D
#undef EZL_MAKE_FLOAT
#undef EZL_MAKE_FLOAT_I
#undef EZL_MAKE_FLOAT_C
